# Site settings
title: My Website
description: A website powered by Github Pages

# Theme settings
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Markdown settings
markdown: kramdown

# Github Pages settings
github:
  repository: DanielFelipeGomez/pruebaMarkDown.gitgub.io

# Build settings
permalink: /:year/:month/:day/:title/
paginate: 5
