# Site settings
title: Recetario Sara y Dani
description: Un libro de recetas lleno de alegria y sabor

# Theme settings
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Markdown settings
markdown: kramdown

# Github Pages settings
github:
  repository: DanielFelipeGomez/pruebaMarkDown.gitgub.io

# Build settings
permalink: /:year/:month/:day/:title/
paginate: 5
